<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="s3.ind.business.impl.UserServiceImplTest" tests="5" skipped="0" failures="0" errors="0" timestamp="2024-05-06T18:48:44" hostname="DESKTOP-88OFGPG" time="0.118">
  <properties/>
  <testcase name="createUser_WhenEmailExists_ThrowsException()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.065"/>
  <testcase name="updateUser_WhenUserNotFound_ThrowsException()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.008"/>
  <testcase name="deleteUser_DeletesUser()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.012"/>
  <testcase name="getAllUsers_ReturnsUserList()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.014"/>
  <testcase name="updateUser_WhenFound_UpdatesSuccessfully()" classname="s3.ind.business.impl.UserServiceImplTest" time="0.005"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
